#This file is an example of an environment file for defining the isolated
#networks and related parameters.
resource_registry:
  # Network Interface templates to use (these files must exist). You can
  # override these by including one of the net-*.yaml environment files,
  # such as net-bond-with-vlans.yaml, or modifying the list here.
  # Port assignments for the Controller
  OS::TripleO::Controller::Net::SoftwareConfig:
    /home/stack/templates/controller.yaml
  OS::TripleO::ControllerB::Net::SoftwareConfig:
    /home/stack/templates/controllerb.yaml
  # Port assignments for the Compute
  # Port assignments for the Compute
  OS::TripleO::Compute::Net::SoftwareConfig:
    /home/stack/templates/compute.yaml
  OS::TripleO::ComputeRt::Net::SoftwareConfig:
    /home/stack/templates/computert.yaml

parameter_defaults:
  # This section is where deployment-specific configuration is done
  #
  # NOTE: (Since Rocky)
  # ControlPlaneSubnetCidr: It is no longer a requirement to provide the
  #                         parameter. The attribute is resolved from the
  #                         ctlplane subnet(s).
  # ControlPlaneDefaultRoute: It is no longer a requirement to provide this
  #                           parameter. The attribute is resolved from the
  #                           ctlplane subnet(s).
  # EC2MetadataIp: It is no longer a requirement to provide this parameter. The
  #                attribute is resolved from the ctlplane subnet(s).
  #
  PublicVirtualFixedIPs: [{'ip_address':'168.127.11.10'}]
  AdminPassword: "wirelessadmin"

  # Customize the IP subnet to match the local environment
  StorageNetCidr: '192.168.12.0/24'
  # Customize the IP range to use for static IPs and VIPs
  StorageAllocationPools: [{'start': '192.168.12.4', 'end': '192.168.12.250'}]
  # Customize the VLAN ID to match the local environment
  StorageNetworkVlanID: 12


  # Customize the IP subnet to match the local environment
  StorageMgmtNetCidr: '192.168.13.0/24'
  # Customize the IP range to use for static IPs and VIPs
  StorageMgmtAllocationPools: [{'start': '192.168.13.4', 'end': '192.168.13.250'}]
  # Customize the VLAN ID to match the local environment
  StorageMgmtNetworkVlanID: 13


  # Customize the IP subnet to match the local environment
  InternalApiNetCidr: '192.168.10.0/24'
  # Customize the IP range to use for static IPs and VIPs
  InternalApiAllocationPools: [{'start': '192.168.10.4', 'end': '192.168.10.250'}]
  # Customize the VLAN ID to match the local environment
  InternalApiNetworkVlanID: 10


  # Customize the IP subnet to match the local environment
  TenantNetCidr: '192.168.11.0/24'
  # Customize the IP range to use for static IPs and VIPs
  TenantAllocationPools: [{'start': '192.168.11.4', 'end': '192.168.11.250'}]
  # Customize the VLAN ID to match the local environment
  TenantNetworkVlanID: 11
  # MTU of the underlying physical network. Neutron uses this value to
  # calculate MTU for all virtual network components. For flat and VLAN
  # networks, neutron uses this value without modification. For overlay
  # networks such as VXLAN, neutron automatically subtracts the overlay
  # protocol overhead from this value.
  TenantNetPhysnetMtu: 1500


  # Customize the IP subnet to match the local environment
  ExternalNetCidr: '168.127.11.0/27'
  # Customize the IP range to use for static IPs and VIPs
  # Leave room if the external network is also used for floating IPs
  ExternalAllocationPools: [{'start': '168.127.11.11', 'end': '168.127.11.16'}]
  # Gateway router for routable networks
  ExternalInterfaceDefaultRoute: '168.127.11.30'
  # Customize the VLAN ID to match the local environment
  ExternalNetworkVlanID: 17


  # Customize the IP subnet to match the local environment
  ManagementNetCidr: '10.0.1.0/24'
  # Customize the IP range to use for static IPs and VIPs
  ManagementAllocationPools: [{'start': '10.0.1.4', 'end': '10.0.1.250'}]
  # Gateway router for routable networks
  ManagementInterfaceDefaultRoute: '10.0.1.1'
  # Customize the VLAN ID to match the local environment
  ManagementNetworkVlanID: 60


  # Define the DNS servers (maximum 2) for the overcloud nodes
  # When the list is not set or empty, the nameservers on the ctlplane subnets will be used.
  # (ctlplane subnets nameservers are controlled by the ``undercloud_nameservers`` option in ``undercloud.conf``)
  DnsServers: 
    - 168.127.132.3
    - 168.127.132.4
  NtpServer:
    - ntp-d.nist.gov
  # List of Neutron network types for tenant networks (will be used in order)
  NeutronNetworkType: 'vxlan,vlan'
  # Neutron VLAN ranges per network, for example 'datacentre:1:499,tenant:500:1000':
  NeutronNetworkVLANRanges: 'datacentre:1:1000'
  # Customize bonding options, e.g. "mode=4 lacp_rate=1 updelay=1000 miimon=100"
  # for Linux bonds w/LACP, or "bond_mode=active-backup" for OVS active/backup.
  #BondInterfaceOvsOptions: "bond_mode=active-backup"
  BondInterfaceOvsOptions: "mode=4 lacp_rate=1 updelay=1000 miimon=100"
  NeutronBridgeMappings:
    - datacentre:br-ex
  NeutronNetworkVLANRanges:
    - datacentre:2:4090
  NeutronFlatNetworks: ''

  ComputeParameters:
    KernelArgs: "default_hugepagesz=1GB hugepagesz=1G hugepages=350 intel_iommu=on iommu=pt"
    IsolCpusList: 2-35,38-71
    # switch to NovaVcpuPinSet as work around for bz-1835705
    #NovaComputeCpuDedicatedSet: 2-35,38-71
    NovaVcpuPinSet: 2-35,38-71
    NovaComputeCpuSharedSet: 0,1,36,37
    NeutronPhysicalDevMappings:
      - sriov1-edge1:ens2f1
      - sriov2-edge1:ens7f1
    NeutronSriovNumVFs:
      - ens2f1:8
      - ens7f1:8
    NovaPCIPassthrough:
      - devname: "ens2f1"
        physical_network: "sriov1-edge1"
      - devname: "ens7f1"
        physical_network: "sriov2-edge1"

  ComputeExtraConfig:
    nova::cpu_allocation_ratio: 1
    nova::compute::resume_guests_state_on_host_boot: true

  ComputeRtImage: "overcloud-realtime-compute"
  ComputeRtParameters:
    KernelArgs: "default_hugepagesz=1GB hugepagesz=1G hugepages=350 nx_huge_pages_recovery_ratio=0 intel_iommu=on iommu=pt elevator=cfq audit=1 nomodeset intel_idle.max_cstate=1 tsc=reliable rcu_nocb_poll=1 clocksource=tsc pcie_aspm.policy=performance"
    IsolCpusList:  2-35,38-71
    # switch to NovaVcpuPinSet as work around for bz-1835705
    #NovaComputeCpuDedicatedSet:  2-39,42-79
    NovaVcpuPinSet: 2-35,38-71
    NovaComputeCpuSharedSet:  0,1,36,37
    NeutronPhysicalDevMappings:
      - fronthaul1-edge1:p4p1
      - fronthaul2-edge1:p4p3
      - sriov1-edge1:p7p1
      - sriov2-edge1:p7p2
    NeutronSriovNumVFs:
      - p7p1:4
      - p7p2:4
      - p4p1:2
      - p4p3:2
    NovaPCIPassthrough:
      - devname: "p4p1"
        physical_network: "fronthaul1-edge1"
      - devname: "p4p3"
        physical_network: "fronthaul2-edge1"
      - devname: "p7p1"
        physical_network: "sriov1-edge1"
      - devname: "p7p2"
        physical_network: "sriov2-edge1"
      - vendor_id: "1172"
        product_id: "5050"

  ComputeRtExtraConfig:
    nova::cpu_allocation_ratio: 1
    nova::compute::resume_guests_state_on_host_boot: true
    nova::pci::aliases:
      - name: vc_fpga
        vendor_id: '1172'
        product_id: '5050'
        device_type: 'type-VF'
