---

# TODO(emilien) convert this whole task in a module
# https://bugs.launchpad.net/tripleo/+bug/1884577
- name: "Remove old {{ item.0 }} container startup configs"
  file:
    path: "/var/lib/tripleo-config/container-startup-config/{{ item.0 }}"
    state: absent

- name: "Create directory for {{ item.0 }} container startup configs"
  file:
    path: "/var/lib/tripleo-config/container-startup-config/{{ item.0 }}/"
    mode: 0600
    recurse: yes
    setype: svirt_sandbox_file_t

- name: "Creating container startup configs for {{ item.0 }}"
  copy:
    content: "{{ startup_data.value | to_nice_json }}"
    dest: "/var/lib/tripleo-config/container-startup-config/{{ item.0 }}/{{ startup_data.key }}.json"
    setype: container_file_t
    mode: 0600
  no_log: true
  loop_control:
    loop_var: startup_data
  loop: "{{ item.1 | dict2items }}"
