# A Heat environment file which can be used to enable a
# a Cinder  HPELeftHandISCSI backend, configured via puppet
resource_registry:
  OS::TripleO::Services::CinderHPELeftHandISCSI: ../deployment/cinder/cinder-hpelefthand-iscsi-puppet.yaml

parameter_defaults:
  CinderHPELeftHandISCSIApiUrl: ''
  CinderHPELeftHandISCSIUserName: ''
  CinderHPELeftHandISCSIPassword: ''
  CinderHPELeftHandISCSIBackendName: 'tripleo_hpelefthand'
  CinderHPELeftHandISCSIChapEnabled: false
  CinderHPELeftHandClusterName: ''
  CinderHPELeftHandDebug: false
