# A Heat environment file which can be used to enable a
# Cinder Dell EMC VNX backend, configured via puppet
resource_registry:
  OS::TripleO::Services::CinderBackendDellEMCVNX: ../deployment/cinder/cinder-backend-dellemc-vnx-puppet.yaml

parameter_defaults:
  CinderEnableDellEMCVNXBackend: true
  CinderDellEMCVNXBackendName: 'tripleo_dellemc_vnx'
  CinderDellEMCVNXSanIp: ''
  CinderDellEMCVNXSanLogin: 'admin'
  CinderDellEMCVNXSanPassword: ''
  CinderDellEMCVNXStorageProtocol: 'iscsi'
  CinderDellEMCVNXStoragePoolNames: ''
  CinderDellEMCVNXDefaultTimeout: 3600
  CinderDellEMCVNXMaxLunsPerStorageGroup: 255
  CinderDellEMCVNXInitiatorAutoRegistration: 'true'
  CinderDellEMCVNXAuthType: 'global'
  CinderDellEMCVNXStorageSecurityFileDir: ''
  CinderDellEMCVNXNaviSecCliPath: '/opt/Navisphere/bin/naviseccli'
