# A Heat environment file which can be used to enable a
# Cinder Dell EMC VMAX backend, configured via puppet
resource_registry:
  OS::TripleO::Services::CinderBackendDellEMCVMAXISCSI: ../deployment/cinder/cinder-backend-dellemc-vmax-iscsi-puppet.yaml

parameter_defaults:
  CinderEnableDellEMCVMAXISCSIBackend: true
  CinderDellEMCVMAXISCSIBackendName: 'tripleo_dellemc_vmax_iscsi'
  CinderDellEMCVMAXISCSIConfigFile: ''
