# A Heat environment file which can be used to enable a
# Cinder Dell EMC Storage Center backend, configured via puppet
resource_registry:
  OS::TripleO::Services::CinderBackendDellEMCSc: ../deployment/cinder/cinder-backend-dellemc-sc-puppet.yaml

parameter_defaults:
  CinderEnableScBackend: true
  CinderScBackendName: 'tripleo_dellemc_sc'
  CinderScMultiConfig: {}
  CinderScSanIp: ''
  CinderScSanLogin: 'Admin'
  CinderScSanPassword: ''
  CinderScSsn: 64702
  CinderScIscsiIpAddress: ''
  CinderScIscsiPort: 3260
  CinderScApiPort: 3033
  CinderScServerFolder: 'dellsc_server'
  CinderScVolumeFolder: 'dellsc_volume'
  CinderScSecondarySanIp: ''
  CinderScSecondarySanLogin: 'Admin'
  CinderScSecondarySanPassword: ''
  CinderScSecondaryScApiPort: 3033
  CinderScExcludedDomainIps: []
  CinderScMultipathXfer: true
  CinderScStorageProtocol: 'iSCSI'
# To configure multiple SC backends, use CinderScMultiConfig to
# assign parameter values specific to that backend. CinderScMultiConfig
# is a dictionary of the parameter values for each backend specified in
# CinderScBackendName
# For example, see below:
#   CinderScBackendName:
#     - tripleo_dellemc_sc_1
#     - tripleo_dellemc_sc_2
#   CinderScMultiConfig:
#     tripleo_dellemc_sc_1:
#       CinderScStorageProtocol: 'iSCSI' # Specific value for this backend
#     tripleo_dellemc_sc_2:
#       CinderScStorageProtocol: 'FC' # Specific value for this backend

