# A Heat environment file which can be used to enable a
# Cinder Dell EMC PowerMax backend, configured via puppet.
resource_registry:
  OS::TripleO::Services::CinderBackendDellEMCPowermax: ../deployment/cinder/cinder-backend-dellemc-powermax-puppet.yaml

parameter_defaults:
  CinderEnablePowermaxBackend: true
  CinderPowermaxBackendName: 'tripleo_dellemc_powermax'
  CinderPowermaxMultiConfig: {}
  CinderPowermaxAvailabilityZone: ''
  CinderPowermaxSanIp: ''
  CinderPowermaxSanLogin: 'Admin'
  CinderPowermaxSanPassword: ''
  CinderPowermaxArray: ''
  CinderPowermaxSrp: ''
  CinderPowermaxPortGroups: ''
  CinderPowermaxStorageProtocol: 'iSCSI'

# To configure multiple Powermax backends, use CinderPowermaxMultiConfig to
# assign parameter values specific to that backend. For example:
#   CinderPowermaxBackendName:
#     - tripleo_dellemc_powermax_1
#     - tripleo_dellemc_powermax_2
#   CinderPowermaxMultiConfig:
#     tripleo_dellemc_powermax_1:
#       CinderPowermaxStorageProtocol: 'iSCSI' # Specific value for this backend
#     tripleo_dellemc_powermax_2:
#       CinderPowermaxStorageProtocol: 'FC' # Specific value for this backend

