## DEPRECATED
# KernelArgs and TunedProfileName has been moved from PreNetworkConfig to boot-params-service.yaml (TripleO service)
# OvS-DPDK configurations has been moved from PreNetworkConfig to respective dpdk TripleO service (ml2-ovs, ml2-ovn)
# host_config_and_reboot.yaml does not do anything, and soon it will be removed

resource_registry:

  OS::TripleO::Controller::PreNetworkConfig: OS::Heat::None

  OS::TripleO::Compute::PreNetworkConfig: OS::Heat::None


#parameter_defaults:
  # Note: There are no global parameters which can be applied to all roles as
  # these configuration have to be specific to role.

  # Sample parameters for Compute and ComputeOvsDpdk roles
  #ComputeParameters:
    #KernelArgs: ""
    #TunedProfileName: ""
    #IsolCpusList: ""
  #ComputeOvsDpdkParameters:
    #KernelArgs: "intel_iommu=on iommu=pt default_hugepagesz=1GB hugepagesz=1G hugepages=60"
    #TunedProfileName: "cpu-partitioning"
    #IsolCpusList: ""