# This environment file enables Manila with the Unity backend.
resource_registry:
  OS::TripleO::Services::ManilaApi: ../deployment/manila/manila-api-container-puppet.yaml
  OS::TripleO::Services::ManilaScheduler: ../deployment/manila/manila-scheduler-container-puppet.yaml
  # Only manila-share is pacemaker managed:
  OS::TripleO::Services::ManilaShare: ../deployment/manila/manila-share-pacemaker-puppet.yaml
  OS::TripleO::Services::ManilaBackendUnity: ../deployment/manila/manila-backend-unity.yaml

parameter_defaults:
  ManilaUnityBackendName: tripleo_manila_unity
  ManilaUnityDriverHandlesShareServers: true
  ManilaUnityNasLogin: ''
  ManilaUnityNasPassword: ''
  ManilaUnityNasServer: ''
  ManilaUnityServerMetaPool: ''
  ManilaUnityShareDataPools: ''
  ManilaUnityEthernetPorts: ''
  ManilaUnityEmcSslCertVerify: false
  ManilaUnityEmcSslCertPath: ''
