# This environment file enables Manila with the Isilon backend.
resource_registry:
  OS::TripleO::Services::ManilaApi: ../deployment/manila/manila-api-container-puppet.yaml
  OS::TripleO::Services::ManilaScheduler: ../deployment/manila/manila-scheduler-container-puppet.yaml
  # Only manila-share is pacemaker managed:
  OS::TripleO::Services::ManilaShare: ../deployment/manila/manila-share-pacemaker-puppet.yaml
  OS::TripleO::Services::ManilaBackendIsilon: ../deployment/manila/manila-backend-isilon.yaml

parameter_defaults:
  ManilaIsilonBackendName: tripleo_isilon
  ManilaIsilonDriverHandlesShareServers: true
  ManilaIsilonNasLogin: ''
  ManilaIsilonNasPassword: ''
  ManilaIsilonNasServer: ''
  ManilaIsilonNasRootDir: ''
  ManilaIsilonNasServerPort: 8080
  ManilaIsilonNasServerSecure: ''
