# This environment file enables Manila with the Netapp backend.
resource_registry:
  OS::TripleO::Services::ManilaApi: ../deployment/manila/manila-api-container-puppet.yaml
  OS::TripleO::Services::ManilaScheduler: ../deployment/manila/manila-scheduler-container-puppet.yaml
  # Only manila-share is pacemaker managed:
  OS::TripleO::Services::ManilaShare: ../deployment/manila/manila-share-pacemaker-puppet.yaml
  OS::TripleO::Services::ManilaBackendNetapp: ../deployment/manila/manila-backend-netapp.yaml

parameter_defaults:
  ManilaNetappBackendName: tripleo_netapp
  ManilaNetappDriverHandlesShareServers: true
  ManilaNetappLogin: ''
  ManilaNetappPassword: ''
  ManilaNetappServerHostname: ''
  ManilaNetappTransportType: 'http'
  ManilaNetappStorageFamily: 'ontap_cluster'
  ManilaNetappServerPort: 80
  ManilaNetappVolumeNameTemplate: 'share_%(share_id)s'
  ManilaNetappVserver: ''
  ManilaNetappVserverNameTemplate: 'os_%s'
  ManilaNetappLifNameTemplate: 'os_%(net_allocation_id)s'
  ManilaNetappAggrNameSearchPattern: '(.*)'
  ManilaNetappRootVolumeAggr: ''
  ManilaNetappRootVolume: 'root'
  ManilaNetappPortNameSearchPattern: '(.*)'
  ManilaNetappTraceFlags: ''
  ManilaNetappEnabledShareProtocols: 'nfs3, nfs4.0'
  ManilaNetappVolumeSnapshotReservePercent: 5
  ManilaNetappSnapmirrorQuiesceTimeout: 3600
