# This environment file enables Manila with the VNX backend.
resource_registry:
  OS::TripleO::Services::ManilaApi: ../deployment/manila/manila-api-container-puppet.yaml
  OS::TripleO::Services::ManilaScheduler: ../deployment/manila/manila-scheduler-container-puppet.yaml
  # Only manila-share is pacemaker managed:
  OS::TripleO::Services::ManilaShare: ../deployment/manila/manila-share-pacemaker-puppet.yaml
  OS::TripleO::Services::ManilaBackendVNX: ../deployment/manila/manila-backend-vnx.yaml

parameter_defaults:
  ManilaVNXBackendName: tripleo_manila_vnx
  ManilaVNXDriverHandlesShareServers: true
  ManilaVNXNasLogin: ''
  ManilaVNXNasPassword: ''
  ManilaVNXNasServer: ''
  ManilaVNXServerContainer: ''
  ManilaVNXShareDataPools: ''
  ManilaVNXEthernetPorts: ''
  ManilaVNXEmcSslCertVerify: false
  ManilaVNXEmcSslCertPath: ''
