# NOTE: This file is deprecated, and is included for backwards-compatibility
# for use in upgrades. For new deployments, set ipv6: true for isolated
# networks using IPv6 (Tenant network should use IPv4 for tunneling),
# and set the default_route_networks to "['ControlPlane', 'External']"
# on the Controller role to use ControlPlane for IPv4 and External for IPv6
# default routes, and include network-environment.yaml instead of this file.
resource_registry:
  # Network Interface templates to use (these files must exist). You can
  # override these by including one of the net-*.yaml environment files,
  # such as net-bond-with-vlans-v6.yaml, or modifying the list here.
  # Port assignments for the Controller
  OS::TripleO::Controller::Net::SoftwareConfig:
    ../network/config/single-nic-vlans/controller.yaml
  # Port assignments for the Compute
  OS::TripleO::Compute::Net::SoftwareConfig:
    ../network/config/single-nic-vlans/compute.yaml

parameter_defaults:
  # This section is where deployment-specific configuration is done
  #
  # NOTE: (Since Rocky)
  # ControlPlaneSubnetCidr: It is no longer a requirement to provide this
  #                         parameter. The attribute is resolved from the
  #                         ctlplane subnet(s).
  # ControlPlaneDefaultRoute: It is no longer a requirement to provide this
  #                           parameter. The attribute is resolved from the
  #                           ctlplane subnet(s).
  # EC2MetadataIp: It is no longer a requirement to provide this parameter. The
  #                attribute is resolved from the ctlplane subnet(s).
  #
  #

  # Customize the IP subnets to match the local environment
  StorageNetCidr: 'fd00:fd00:fd00:3000::/64'
  # Customize the IP range to use for static IPs and VIPs
  StorageAllocationPools: [{'start': 'fd00:fd00:fd00:3000::10', 'end': 'fd00:fd00:fd00:3000:ffff:ffff:ffff:fffe'}]
  # Customize the VLAN ID to match the local environment
  StorageNetworkVlanID: 12


  # Customize the IP subnets to match the local environment
  StorageMgmtNetCidr: 'fd00:fd00:fd00:4000::/64'
  # Customize the IP range to use for static IPs and VIPs
  StorageMgmtAllocationPools: [{'start': 'fd00:fd00:fd00:4000::10', 'end': 'fd00:fd00:fd00:4000:ffff:ffff:ffff:fffe'}]
  # Customize the VLAN ID to match the local environment
  StorageMgmtNetworkVlanID: 13


  # Customize the IP subnets to match the local environment
  InternalApiNetCidr: 'fd00:fd00:fd00:2000::/64'
  # Customize the IP range to use for static IPs and VIPs
  InternalApiAllocationPools: [{'start': 'fd00:fd00:fd00:2000::10', 'end': 'fd00:fd00:fd00:2000:ffff:ffff:ffff:fffe'}]
  # Customize the VLAN ID to match the local environment
  InternalApiNetworkVlanID: 10


  # Tenant tunneling network is IPv4 until IPv6 is fully supported
  # Customize the IP subnets to match the local environment
  TenantNetCidr: '172.16.0.0/24'
  # Customize the IP range to use for static IPs and VIPs
  TenantAllocationPools: [{'start': '172.16.0.4', 'end': '172.16.0.250'}]
  # Customize the VLAN ID to match the local environment
  TenantNetworkVlanID: 11
  # MTU of the underlying physical network. Neutron uses this value to
  # calculate MTU for all virtual network components. For flat and VLAN
  # networks, neutron uses this value without modification. For overlay
  # networks such as VXLAN, neutron automatically subtracts the overlay
  # protocol overhead from this value.
  TenantNetPhysnetMtu: 1500


  # Customize the IP subnets to match the local environment
  ExternalNetCidr: '2001:db8:fd00:1000::/64'
  # Customize the IP range to use for static IPs and VIPs
  # Leave room if the external network is also used for floating IPs
  ExternalAllocationPools: [{'start': '2001:db8:fd00:1000::10', 'end': '2001:db8:fd00:1000:ffff:ffff:ffff:fffe'}]
  # Gateway router for routable networks
  ExternalInterfaceDefaultRoute: '2001:db8:fd00:1000::1'
  # Customize the VLAN ID to match the local environment
  ExternalNetworkVlanID: 17


  # Customize the IP subnets to match the local environment
  ManagementNetCidr: 'fd00:fd00:fd00:6000::/64'
  # Customize the IP range to use for static IPs and VIPs
  ManagementAllocationPools: [{'start': 'fd00:fd00:fd00:6000::10', 'end': 'fd00:fd00:fd00:6000:ffff:ffff:ffff:fffe'}]
  # Gateway router for routable networks
  ManagementInterfaceDefaultRoute: 'fd00:fd00:fd00:6000::1'
  # Customize the VLAN ID to match the local environment
  ManagementNetworkVlanID: 60


  # Define the DNS servers (maximum 2) for the overcloud nodes
  # When the list is not set (empty) the nameservers on the ctlplane subnet(s) will be used.
  # (ctlplane subnet(s) nameservers are confgured by the ``undercloud_nameservers`` option in ``undercloud.conf``)
  DnsServers: []
  # List of Neutron network types for tenant networks (will be used in order)
  NeutronNetworkType: 'geneve,vlan'
  # Neutron VLAN ranges per network, for example 'datacentre:1:499,tenant:500:1000':
  NeutronNetworkVLANRanges: 'datacentre:1:1000'
  # Customize bonding options, e.g. "mode=4 lacp_rate=1 updelay=1000 miimon=100"
  # for Linux bonds w/LACP, or "bond_mode=active-backup" for OVS active/backup.
  BondInterfaceOvsOptions: "bond_mode=active-backup"