resource_registry:
 OS::TripleO::Services::NeutronCorePluginNSX: ../deployment/neutron/neutron-plugin-nsx-container-puppet.yaml

parameter_defaults:
 # Default overlay tz uuid
 DefaultOverlayTz: ''

 DefaultVlanTz: ''
 # Default tier0 router uuid
 DefaultTier0Router: ''
 # NSX API managers
 NsxApiManagers: ''
 # NSX API user
 NsxApiUser: ''
 # NSX API password
 NsxApiPassword: ''
 # Enable native DHCP and Metadata
 NativeDhcpMetadata: True
 # Default DHCP profile uuid
 DhcpProfile: ''
 # Default Metadata Proxy uuid
 MetadataProxy: ''
