heat_template_version: rocky

description: >
  OpenStack containerized Heat API service

outputs:
  config_settings:
    description: Extra hieradata needed to log to files in the host.
    value: null
  docker_config:
    description: Extra containers needed for logging to files in the host.
    value:
      step_2: {}
  volumes:
    description: The volumes needed to log to files in the host.
    value:
      - /var/log/containers/heat:/var/log/heat:z
      - /var/log/containers/httpd/heat-api:/var/log/httpd:z
  host_prep_tasks:
    description: Extra ansible tasks needed for logging to files in the host.
    value:
      - name: create persistent directories
        file:
          path: "{{ item.path }}"
          state: directory
          setype: "{{ item.setype }}"
          mode: "{{ item.mode }}"
        with_items:
          - { 'path': /var/log/containers/heat, 'setype': svirt_sandbox_file_t, 'mode': '0750' }
          - { 'path': /var/log/containers/httpd/heat-api, 'setype': svirt_sandbox_file_t, 'mode': '0750' }
