heat_template_version: rocky

description: >
  OpenStack containerized Glance API service

parameters:
  ContainerHeatEngineImage:
    description: image
    type: string

outputs:
  cmd_extra_args:
    description: Extra command line arguments for running the service in the container.
    value: ''
  config_settings:
    description: Extra hieradata needed to log to files in the host.
    value: null
  docker_config:
    description: Extra containers needed for logging to files in the host.
    value:
      # Kolla_bootstrap/db_sync runs before permissions set by kolla_config
      step_2:
        heat_init_log:
          image: {get_param: ContainerHeatEngineImage}
          net: none
          user: root
          volumes:
            - /var/log/containers/heat:/var/log/heat:z
          command: ['/bin/bash', '-c', 'chown -R heat:heat /var/log/heat']
  volumes:
    description: The volumes needed to log to files in the host.
    value:
      - /var/log/containers/heat:/var/log/heat:z
  host_prep_tasks:
    description: Extra ansible tasks needed for logging to files in the host.
    value:
      - name: create persistent directories
        file:
          path: "{{ item.path }}"
          state: directory
          setype: "{{ item.setype }}"
          mode: "{{ item.mode }}"
        with_items:
          - { 'path': /var/log/containers/heat, 'setype': svirt_sandbox_file_t, 'mode': '0750' }
