heat_template_version: rocky

description: >
  OpenStack containerized Neutron service

parameters:
  NeutronServiceName:
    description: service name
    type: string

outputs:
  cmd_extra_args:
    description: Extra command line arguments for running the service in the container.
    value:
      str_replace:
        template: "--log-file=/var/log/neutron/SERVICE.log"
        params:
          SERVICE: {get_param: NeutronServiceName}
  config_settings:
    description: Extra hieradata needed to log to files in the host.
    value: null
  docker_config:
    description: Extra containers needed for logging to files in the host.
    value:
      step_2: {}
  volumes:
    description: The volumes needed to log to files in the host.
    value:
      - /var/log/containers/neutron:/var/log/neutron:z
  host_prep_tasks:
    description: Extra ansible tasks needed for logging to files in the host.
    value:
      - name: create persistent directories
        file:
          path: "{{ item.path }}"
          state: directory
          setype: "{{ item.setype }}"
          mode: "{{ item.mode }}"
        with_items:
          - { 'path': /var/log/containers/neutron, 'setype': svirt_sandbox_file_t, 'mode': '0750' }
