heat_template_version: rocky

description: >
  Template for placement's logging to files

parameters:
  ContainerPlacementImage:
    description: image
    type: string

outputs:
  config_settings:
    description: Extra hieradata needed to log to files in the host.
    value: null
  volumes:
    description: The volumes needed to log to files in the host.
    value: &placement_volumes
      - /var/log/containers/placement:/var/log/placement:z
      - /var/log/containers/httpd/placement:/var/log/httpd:z
  docker_config:
    description: Extra containers needed for logging to files in the host.
    value:
      step_2:
        placement_init_log:
          start_order: 1
          image: {get_param: ContainerPlacementImage}
          net: none
          user: root
          command: ['/bin/bash', '-c', 'chown -R placement:placement /var/log/placement']
          volumes: *placement_volumes
  host_prep_tasks:
    description: Extra ansible tasks needed for logging to files in the host.
    value:
      - name: create persistent logs directory
        file:
          path: "{{ item.path }}"
          state: directory
          setype: "{{ item.setype }}"
          mode: "{{ item.mode }}"
        with_items:
          - { 'path': /var/log/containers/placement, 'setype': svirt_sandbox_file_t, 'mode': '0750' }
          - { 'path': /var/log/containers/httpd/placement, 'setype': svirt_sandbox_file_t, 'mode': '0750' }
