heat_template_version: rocky

description: >
  OpenStack containerized Nova libvirt service

parameters:
  LibvirtLogLevel:
    default: 3
    description: Defines log level in libvirt to filter log output.
                 See https://libvirt.org/logging.html to find its detail.
    type: number
    constraints:
      - range: { min: 1, max: 4 }

outputs:
  config_settings:
    description: Extra hieradata needed to log to stdout.
    value:
      nova::compute::libvirt::log_outputs:
        str_replace:
          template:
            'LEVEL:stderr'
          params:
            LEVEL: {get_param: LibvirtLogLevel}
  docker_config:
    description: Extra containers needed for logging to stdout or a sidecar container.
    value: null
  volumes:
    description: The volumes needed to log to stdout or a sidecar container.
    value: null
  host_prep_tasks:
    description: Extra ansible tasks needed for logging to stdout or a sidecar container.
    value: null
