###############################################################################
# Role: UndercloudMinion                                                      #
###############################################################################
- name: UndercloudMinion
  description: |
    A role to deploy an undercloud minion to handle scaling out of heat-engine
    and ironic-conductor via heat using the 'openstack undercloud
    minion deploy' command.
  CountDefault: 1
  tags:
    - primary
  ServicesDefault:
    - OS::TripleO::Services::CACerts
    - OS::TripleO::Services::CertmongerUser
    - OS::TripleO::Services::ContainerImagePrepare
    - OS::TripleO::Services::ContainersLogrotateCrond
    - OS::TripleO::Services::HeatEngine
    - OS::TripleO::Services::IronicConductor
    - OS::TripleO::Services::Kernel
    - OS::TripleO::Services::MySQLClient
    - OS::TripleO::Services::OpenStackClients
    - OS::TripleO::Services::Podman
    - OS::TripleO::Services::Rear
    - OS::TripleO::Services::Rhsm
    - OS::TripleO::Services::Sshd
    - OS::TripleO::Services::Timesync
    - OS::TripleO::Services::Timezone
    - OS::TripleO::Services::Tmpwatch
    - OS::TripleO::Services::TripleoFirewall
    - OS::TripleO::Services::TripleoValidations
    - OS::TripleO::Services::Tuned
    - OS::TripleO::Services::UndercloudMinionMessaging
    - OS::TripleO::Services::UndercloudUpgrade
